name: food_app
description: "Food delivery app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  http: ^1.2.2
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0

  # 💳 STRIPE
  flutter_stripe: ^10.1.1
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
